# Generated by Django 5.2 on 2026-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_question_lesson_slug_choice_quiz_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="lesson_videos/"),
        ),
    ]
