# Generated by Django 5.2 on 2026-03-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_lesson_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
