# Generated by Django 5.2 on 2026-03-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_quizresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="number_of_try",
            field=models.IntegerField(default=3),
        ),
    ]
